import Layout from "@/layout";

import Head from "next/head";
import Hero from "./components/Hero";
import Timelines from "./components/Timelines";
import Blogs from "./components/Blogs";
import Projects from "./components/Projects";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Hero />
        <Timelines />
        <Blogs />
        <Projects />
      </Layout>
    </>
  );
}
